environments:
  dev_feature:
    workflows:
      - name: "data_pipeline-rep-smoke-dev-feature-val-v1"
        tasks:
          - task_key: "rep_dev_feature_validation_task"
            spark_python_task:
              python_file: "file://main.py"
              parameters: [ "data_pipeline.validation.task.rep_val", "--env", "dev", "--space", "feature", "--zone", "raw", "--object_type", "re", "--job_type", "rep", "--test_type", "smoke" ]
            # libraries: []  # Explicitly set empty libraries
            environment_key: "default"  
        environments:  
          - environment_key: "default"
            spec:
              client: "1"  # Required for serverless
              # dependencies: []  # Can be empty or list your deps
