## Serverless-compatible job deployment for validation (dev_feature)
# This file is tailored for workspaces that only allow Serverless (no classic clusters).
# Key points:
# - Uses job_clusters with a serverless single-node spec (num_workers: 0)
# - Adds spark.databricks.cluster.profile=serverless and node_type_id=serverless
# - Includes PHOTON runtime_engine for better performance (optional)
# - Keeps parameters consistent with existing validation tasks

environments:
  dev_feature:
    workflows:
      - name: "we-pipeline-rep-smoke-dev-feature-val-v1"
        libraries:
          - whl: "dist/data_pipeline-1.0.0-py3-none-any.whl"

        # # Define a job cluster for the tasks
        # job_clusters:
        #   - job_cluster_key: serverless_single_node
        #     new_cluster:
        #       spark_version: "13.3.x-scala2.12"
        #       num_workers: 0
        #       data_security_mode: SINGLE_USER
        #       runtime_engine: STANDARD
        #       custom_tags:
        #         usage: "serverless-single-node"
        #       # This line tells Databricks to use Serverless compute
        #       serverless: true
        #       spark_conf:
        #         spark.databricks.cluster.profile: serverless

        # compute:
        #   - compute_key: serverless_compute
        #     compute_type: SERVERLESS
        #     spec:
        #       kind: SERVERLESS
        #       serverless:
        #         enabled: true
        #       spark_conf:
        #         spark.databricks.cluster.profile: serverless

        tasks:
          - task_key: "rep_dev_feature_validation_task"
            # compute_key: serverless_compute
            spark_python_task:
              python_file: "file://main.py"
              parameters: [ "data_pipeline.validation.task.rep_val", "--env", "dev", "--space", "feature", "--zone", "raw", "--object_type", "re", "--job_type", "rep", "--test_type", "smoke" ]


        # compute:
        #   - compute_key: serverless_compute
        #     compute_type: SERVERLESS
        #     spec:
        #       kind: SERVERLESS
        #       serverless:
        #         enabled: true


