

environments:
  dev_feature:
    workflows:
      - name: "we-pipeline-rep-smoke-dev-feature-val-v1"
        job_clusters:
          - job_cluster_key: "dev_feature_cluster"
            new_cluster:
              spark_version: "15.3.x-scala2.12"
              node_type_id: "i3.xlarge"
              num_workers: 1
              data_security_mode: "SINGLE_USER"


        tasks:
          - task_key: "rep_dev_feature_validation_task"
            job_cluster_key: "dev_feature_cluster"
            spark_python_task:
              python_file: "file://main.py"
              parameters: [ "data_pipeline.validation.task.rep_val", "--env", "dev", "--space", "feature", "--zone", "raw", "--object_type", "re", "--job_type", "rep", "--test_type", "smoke" ]

        # compute:
        #   - compute_key: serverless_compute
        #     compute_type: SERVERLESS
        #     spec:
        #       kind: SERVERLESS
        #       serverless:
        #         enabled: true


